name: Verify Engine Code

on:
  pull_request:
  push:
    paths:
    - '.github/workflows/engine.yml'
    - 'src/**'
    - 'tools/**'
  workflow_dispatch:


jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - run: bun install

    - name: Lint
      run: bun run lint

    - name: Compile
      run: bun run tsc