name: Verify Engine Code

on:
  pull_request:
  push:
    branches: ["Another-Clean-Base-To-Experiment-On"]
    paths:
      - ".github/workflows/engine.yml"
      - "engine/**"
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: engine

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Compile
        run: bun run tsc
