name: Verify Engine Code

on:
  pull_request:
  push:
    paths:
      - 'engine/.github/workflows/engine.yml'
      - 'engine/src/**'
      - 'engine/tools/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: engine

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: |
          if [ "$(npm pkg get scripts.lint 2>/dev/null)" != "undefined" ]; then
            bun run lint
          else
            echo "no lint script"
          fi

      - name: Compile
        run: bun run tsc
