name: Test migrations

on:
  pull_request:
  push:
    branches: ["Another-Clean-Base-To-Experiment-On"]
    paths:
      - "engine/prisma/**"
      - ".github/workflows/migrations.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: lostcity
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: engine

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "engine/package-lock.json"

      - name: Install dependencies
        run: npm i

      - name: Run Singleworld Migrations
        run: |
          set -e
          npx prisma migrate reset --schema prisma/singleworld/schema.prisma --force

      - name: Run Multiworld Migrations
        env:
          DATABASE_URL: "mysql://root:password@localhost:3306/lostcity"
        run: |
          set -e
          npx prisma migrate reset --schema prisma/multiworld/schema.prisma --force
